default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args:
        - --fix
  - repo: https://github.com/python/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pandas==1.3.3
          - sqlalchemy==1.4.25
          - pytest
          - typer==0.9.0
  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.1'  # pre-commit autoupdate does not work properly
    hooks:
      - id: poetry-check
      - id: poetry-lock
