default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args:
        - --fix
  - repo: https://github.com/python/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pandas==1.3.3
          - sqlalchemy==1.4.25
          - pytest
          - typer==0.9.0
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # pre-commit autoupdate does not work properly
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]
