name: Export
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Ensembl release number'
        required: true
        default: '104'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup dependencies
      uses: ./.github/actions/setup
    - name: Extract tables
      id: extract
      run: poetry run python src/ensembl_genes.py all --release=${{ github.event.inputs.release }}
    - name: Output artifact
      # upload outputs to artifact only when the extraction fails
      if: always() && steps.extract.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: failed-output-${{ github.event.inputs.release }}
        path: output/${{ github.event.inputs.release }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: output-${{ github.event.inputs.release }}
        publish_dir: output/${{ github.event.inputs.release }}
        # Won't actually enable jekyll because we're not using GitHub Pages.
        # https://github.com/peaceiris/actions-gh-pages/issues/660
        enable_jekyll: true
