name: Test
on:
  push:
  pull_request:
  schedule:
  # https://crontab.guru/#57_6_*_*_1
  - cron: '57 6 * * 1'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dependencies
      uses: ./.github/actions/setup
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
    - name: Test with pytest
      run: poetry run pytest --color=yes
